### ISSUE TITLE
Add configuration documentation?

### ISSUE THREAD

**Issue by mpechner** [antonbabenko/terraform-docs-as-pdf#3]
https://www.terraform.io/docs/configuration/index.html

I'm  one of those guys that like to read the basic end to end.

**Comment by antonbabenko** [comment]
Me too, Michael!

That is why there are 7988 pages in this document - https://www.dropbox.com/sh/pfj9e1m5d7nqhp3/AACfZUectN6PmaaDHcTKHVGha/complete-terraform-website.pdf

It is pretty impossible to navigate it in the browser, so I recommend you to download it from here - https://www.dropbox.com/sh/pfj9e1m5d7nqhp3/AAAqW1OI3oYPa4UXfYb4fLGaa - and open offline.
